### PR TITLE
Pfeiffer fixed

### PR DESCRIPTION
**Pull request by TiffanyLuce**
Pressure gauge is now correctly readout by the slow control.
Copy pasted Pancake's gauge plugin.

### CODE REVIEW

**Review by jarongrigat — COMMENTED** [review]
The setup() is not needed, I guess? I wonder why it was in there and if we should keep it

**Comment by TiffanyLuce** [comment]
If the setup() function is in, it doesn't work. That was the problem.
The error is then :
`2023-03-02 10:20:38.513995 | ERROR | device | base_setup | 44 | <class 'AttributeError'>
2023-03-02 10:20:38.514604 | ERROR | device | base_setup | 45 | 'pfeiffer_tpg' object has no attribute '_connected'
2023-03-02 10:20:38.515185 | ERROR | pfeiffer_tpg | open_device | 64 | Could not open device. Error: Initialization failed (<class 'ValueError'>)`

**Comment by jarongrigat** [comment]
Oh yes, this is completely wrong since it overrides the LANDevice setup. It used to be that you have a base setup and then an additional setup if the device needs something special. But I guess this doesn't exist at all anymore 🤔. We should check when this got lost.
Anyway, if pfeiffer_tpg doesn't actually need it, we are fine here for now.

**Review by jarongrigat — APPROVED** [review]

**Comment by TiffanyLuce** [comment]
I also read that TPG361 (this one) and TPG362 (Pancake dual gauge) work the same, communication-wise; so I think they should be kept similar

**Pull request merged**
